# Generated by Django 5.0.1 on 2024-02-02 12:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('frontmain', '0003_testmodel_alter_order_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='PayData',
        ),
    ]
