# Generated by Django 5.0.1 on 2024-02-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_rename_payments_paydata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paydata',
            options={'verbose_name_plural': 'Paydata'},
        ),
    ]
