# Generated by Django 4.2.6 on 2024-02-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_paydata_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paydata',
            name='amount',
        ),
        migrations.AddField(
            model_name='paydata',
            name='phonenumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paydata',
            name='transcode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
