# Generated by Django 5.0.1 on 2024-01-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontmain', '0002_alter_order_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=500)),
                ('cost', models.CharField(max_length=500)),
                ('ordernumber', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'TestModel',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
