# Generated by Django 5.0.1 on 2024-02-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontmain', '0003_testmodel_alter_order_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subject',
            field=models.CharField(blank=True, choices=[('Accounting', 'Accounting'), ('Management', 'Management'), ('Nursing', 'Nursing'), ('English', 'English'), ('Marketing', 'Marketing'), ('Art', 'Art'), ('History', 'History'), ('Law', 'Law'), ('Economics', 'Economics'), ('Writing', 'Writing')], default='Accounting', max_length=500, null=True),
        ),
    ]
