# Generated by Django 4.2.6 on 2024-02-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontmain', '0005_order_time_paid_alter_order_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
