# Generated by Django 4.2.6 on 2024-03-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontmain', '0007_order_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deadline',
        ),
    ]
